/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2346e570",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2346e570").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-58f88bab",
    path: "/artical/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58f88bab").then(next)
    },
  },
  {
    path: "/artical/index.html",
    redirect: "/artical/"
  },
  {
    name: "v-0d72f544",
    path: "/artical/ConcurrentHashMap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d72f544").then(next)
    },
  },
  {
    name: "v-42e66c9e",
    path: "/artical/vue-cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42e66c9e").then(next)
    },
  },
  {
    name: "v-4341d53d",
    path: "/artical/linux%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4341d53d").then(next)
    },
  },
  {
    path: "/artical/linux命令.html",
    redirect: "/artical/linux%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/artical/linux命令.html",
    redirect: "/artical/linux%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]